#MEAN: [0.5, 0.5, 0.5] 72.9068   96.77187  82.967636
#STD: [0.5, 0.5, 0.5]
MEAN: [0.32536328, 0.37949753, 0.28590902]
STD: [0.09531121, 0.10779824, 0.11463393]

TRAIN_CROP_SIZE: (256, 256)
EVAL_CROP_SIZE: (256, 256)
#AUG:
#    AUG_METHOD: "unpadding"
#    FIX_RESIZE_SIZE: (256, 256)
#    MIRROR: True
#    FLIP: True
#    FLIP_RATIO: 0.5

AUG:
#    AUG_METHOD: "unpadding" # choice unpadding rangescaling and stepscaling
    AUG_METHOD: "stepscaling" # choice unpadding rangescaling and stepscaling
    FIX_RESIZE_SIZE: (256, 256) # (width, height), for unpadding
    INF_RESIZE_VALUE: 500  # for rangescaling
    MAX_RESIZE_VALUE: 600  # for rangescaling
    MIN_RESIZE_VALUE: 400  # for rangescaling
    MAX_SCALE_FACTOR: 2.0  # for stepscaling
    MIN_SCALE_FACTOR: 0.5  # for stepscaling
    SCALE_STEP_SIZE: 0.25  # for stepscaling
    MIRROR: True
    FLIP: True
    FLIP_RATIO: 0.5

BATCH_SIZE: 64
DATASET:
    DATA_DIR: "./dataset/rs_data"
    NUM_CLASSES: 7
    TRAIN_FILE_LIST: "./dataset/rs_data/train_list.txt"
    VAL_FILE_LIST: "./dataset/rs_data/val_list.txt"
    TEST_FILE_LIST: "./dataset/rs_data/testA_list.txt"
    # VIS_FILE_LIST: "./dataset/rs_data/testA_list.txt"

FREEZE:
    MODEL_FILENAME: "model"
    PARAMS_FILENAME: "params"
MODEL:
    MODEL_NAME: "ocrnet"
    DEFAULT_NORM_TYPE: "bn"
    HRNET:
        STAGE2:
            NUM_CHANNELS: [18, 36]
        STAGE3:
            NUM_CHANNELS: [18, 36, 72]
        STAGE4:
            NUM_CHANNELS: [18, 36, 72, 144]
    OCR:
        OCR_MID_CHANNELS: 512
        OCR_KEY_CHANNELS: 256
    MULTI_LOSS_WEIGHT: [1.0, 1.0]
TRAIN:
    PRETRAINED_MODEL_DIR: u"./pretrained_model/ocrnet_w18_bn_cityscapes"
    MODEL_SAVE_DIR: "output/ocrnet_w18_bn_remote_sensing/more_data_aug"
    #RESUME_MODEL_DIR: "output/ocrnet_w18_bn_remote_sensing/50"
    SNAPSHOT_EPOCH: 1
    SYNC_BATCH_NORM: True
TEST:
    TEST_MODEL: "output/ocrnet_w18_bn_remote_sensing/best_model"
SOLVER:
    LR: 0.01
    LR_POLICY: "poly"
    OPTIMIZER: "adam"
    NUM_EPOCHS: 100

#    LR_POLICY: "poly"
#    DECAY_EPOCH: [60, 80]
#    OPTIMIZER: "adam"
#    NUM_EPOCHS: 100
#    LOSS: [ "lovasz_softmax_loss","softmax_loss" ]
#        LOSS_WEIGHT:
#            LOVASZ_SOFTMAX_LOSS: 0.2
#            SOFTMAX_LOSS: 0.8
